### ISSUE TITLE
Failing to run docker compose

### ISSUE THREAD

**Issue by thejdavid** [IBM-Blockchain/fabric-boilerplate#5]
```
fabric-boilerplate [master] :> docker-compose up
Pulling membersrvc (rikmoedt/fabric-membersrvc:0.5-dp)...
0.5-dp: Pulling from rikmoedt/fabric-membersrvc
6599cadaf950: Already exists
23eda618d451: Already exists
f0be3084efe9: Already exists
52de432f084b: Already exists
a3ed95caeb02: Pull complete
fe87512d962f: Already exists
3ab00b537a04: Already exists
394221632d6f: Already exists
93f2f8cf004e: Already exists
5b1d7b4298c6: Pull complete
4eb6b673b08e: Pull complete
0e2bb3b0c12e: Pull complete
e051a9bc75f9: Pull complete
459fd4c83e39: Pull complete
2b1579c28634: Pull complete
e421f234eae2: Pull complete
5f6204dd4e19: Pull complete
12d90f151bb4: Pull complete
7d5d2221f344: Pull complete
30ddd56ad412: Pull complete
Digest: sha256:aa1d043b42ed7e6f98b52b713f4a82ba3e17ab7dabcbf44f7ec90b9c0c86cb71
Status: Downloaded newer image for rikmoedt/fabric-membersrvc:0.5-dp
Pulling vp0 (rikmoedt/fabric-peer:0.5-dp)...
0.5-dp: Pulling from rikmoedt/fabric-peer
6599cadaf950: Already exists
23eda618d451: Already exists
f0be3084efe9: Already exists
52de432f084b: Already exists
a3ed95caeb02: Pull complete
fe87512d962f: Already exists
3ab00b537a04: Already exists
394221632d6f: Already exists
93f2f8cf004e: Already exists
5b1d7b4298c6: Already exists
4eb6b673b08e: Already exists
0e2bb3b0c12e: Already exists
e051a9bc75f9: Already exists
459fd4c83e39: Already exists
2b1579c28634: Already exists
e421f234eae2: Already exists
5f6204dd4e19: Already exists
12d90f151bb4: Already exists
7d5d2221f344: Already exists
9548fb9a33d1: Pull complete
Digest: sha256:fbd05b855b80758361b826a19e32835c1fcbf79fc5ddde16cafccfee3bfebc93
Status: Downloaded newer image for rikmoedt/fabric-peer:0.5-dp
Creating fabricboilerplate_membersrvc_1
Creating fabricboilerplate_vp0_1
Creating fabricboilerplate_vp1_1
Attaching to fabricboilerplate_membersrvc_1, fabricboilerplate_vp0_1, fabricboilerplate_vp1_1
vp0_1         | 13:04:42.712 [peer] func1 -> INFO 001 Auto detected peer address: 172.17.0.3:7051
vp0_1         | 13:04:42.713 [peer] func1 -> INFO 002 Auto detected peer address: 172.17.0.3:7051
vp0_1         | 13:04:42.715 [nodeCmd] serve -> INFO 003 Security enabled status: true
vp0_1         | 13:04:42.715 [nodeCmd] serve -> INFO 005 Privacy enabled status: true
vp0_1         | 13:04:42.715 [eventhub_producer] start -> INFO 004 event processor started
vp0_1         | 13:04:42.991 [crypto] RegisterValidator -> INFO 006 Registering validator [test_vp0] with name [test_vp0]...
vp0_1         | 13:04:43.406 [crypto] RegisterValidator -> INFO 007 Registering validator [test_vp0] with name [test_vp0]...done!
vp0_1         | 13:04:43.406 [crypto] InitValidator -> INFO 008 Initializing validator [test_vp0]...
vp0_1         | 13:04:43.489 [crypto] InitValidator -> INFO 009 Initializing validator [test_vp0]...done!
vp0_1         | 13:04:43.490 [chaincode] NewChaincodeSupport -> INFO 00a Chaincode support using peerAddress: 172.17.0.3:7051
vp0_1         | 13:04:43.490 [sysccapi] RegisterSysCC -> WARN 00b Currently system chaincode does support security(noop,github.com/hyperledger/fabric/bddtests/syschaincode/noop)
vp0_1         | 13:04:43.491 [state] loadConfig -> INFO 00c Loading configurations...
vp0_1         | 13:04:43.491 [state] loadConfig -> INFO 00d Configurations loaded. stateImplName=[buckettree], stateImplConfigs=map[numBuckets:%!s(int=1000003) maxGroupingAtEachLevel:%!s(int=5) bucketCacheSize:%!s(int=100)], deltaHistorySize=[500]
vp0_1         | 13:04:43.491 [state] NewState -> INFO 00e Initializing state implementation [buckettree]
vp0_1         | 13:04:43.491 [buckettree] initConfig -> INFO 00f configs passed during initialization = map[string]interface {}{"maxGroupingAtEachLevel":5, "bucketCacheSize":100, "numBuckets":1000003}
vp0_1         | 13:04:43.491 [buckettree] initConfig -> INFO 010 Initializing bucket tree state implemetation with configurations &{maxGroupingAtEachLevel:5 lowestLevel:9 levelToNumBucketsMap:map[5:1601 7:40001 2:13 1:3 0:1 9:1000003 8:200001 6:8001 3:65 4:321] hashFunc:0xa701e0}
vp0_1         | 13:04:43.491 [buckettree] newBucketCache -> INFO 011 Constructing bucket-cache with max bucket cache size = [100] MBs
vp0_1         | 13:04:43.492 [buckettree] loadAllBucketNodesFromDB -> INFO 012 Loaded buckets data in cache. Total buckets in DB = [0]. Total cache size:=0
vp0_1         | 13:04:43.492 [genesis] func1 -> INFO 013 Creating genesis block.
vp0_1         | 13:04:43.493 [consensus/controller] NewConsenter -> INFO 014 Creating default consensus plugin (noops)
vp0_1         | 13:04:43.494 [consensus/statetransfer] blockThread -> INFO 015 Validated blockchain to the genesis block
vp0_1         | 13:04:43.494 [consensus/noops] newNoops -> INFO 016 NOOPS consensus type = *noops.Noops
vp0_1         | 13:04:43.495 [consensus/noops] newNoops -> INFO 017 NOOPS block size = 500
vp0_1         | 13:04:43.495 [consensus/noops] newNoops -> INFO 018 NOOPS block wait = 1s
vp0_1         | 13:04:43.495 [nodeCmd] serve -> INFO 019 Starting peer with ID=name:"vp0" , network ID=dev, address=172.17.0.3:7051, rootnodes=, validator=true
vp0_1         | 13:04:43.496 [rest] StartOpenchainRESTServer -> INFO 01a Initializing the REST service on 0.0.0.0:7050, TLS is disabled.
vp1_1         | 13:04:43.767 [peer] func1 -> INFO 001 Auto detected peer address: 172.17.0.4:7051
vp1_1         | 13:04:43.768 [peer] func1 -> INFO 002 Auto detected peer address: 172.17.0.4:7051
vp1_1         | 13:04:43.769 [nodeCmd] serve -> INFO 003 Security enabled status: true
vp1_1         | 13:04:43.769 [nodeCmd] serve -> INFO 004 Privacy enabled status: true
vp1_1         | 13:04:43.770 [eventhub_producer] start -> INFO 005 event processor started
vp1_1         | 13:04:44.046 [crypto] RegisterValidator -> INFO 006 Registering validator [test_vp1] with name [test_vp1]...
vp1_1         | 13:04:44.429 [crypto] RegisterValidator -> INFO 007 Registering validator [test_vp1] with name [test_vp1]...done!
vp1_1         | 13:04:44.429 [crypto] InitValidator -> INFO 008 Initializing validator [test_vp1]...
vp1_1         | 13:04:44.509 [crypto] InitValidator -> INFO 009 Initializing validator [test_vp1]...done!
vp1_1         | 13:04:44.510 [chaincode] NewChaincodeSupport -> INFO 00a Chaincode support using peerAddress: 172.17.0.4:7051
vp1_1         | 13:04:44.510 [sysccapi] RegisterSysCC -> WARN 00b Currently system chaincode does support security(noop,github.com/hyperledger/fabric/bddtests/syschaincode/noop)
vp1_1         | 13:04:44.511 [state] loadConfig -> INFO 00c Loading configurations...
vp1_1         | 13:04:44.511 [state] loadConfig -> INFO 00d Configurations loaded. stateImplName=[buckettree], stateImplConfigs=map[numBuckets:%!s(int=1000003) maxGroupingAtEachLevel:%!s(int=5) bucketCacheSize:%!s(int=100)], deltaHistorySize=[500]
vp1_1         | 13:04:44.511 [state] NewState -> INFO 00e Initializing state implementation [buckettree]
vp1_1         | 13:04:44.511 [buckettree] initConfig -> INFO 00f configs passed during initialization = map[string]interface {}{"numBuckets":1000003, "maxGroupingAtEachLevel":5, "bucketCacheSize":100}
vp1_1         | 13:04:44.512 [buckettree] initConfig -> INFO 010 Initializing bucket tree state implemetation with configurations &{maxGroupingAtEachLevel:5 lowestLevel:9 levelToNumBucketsMap:map[3:65 1:3 8:200001 6:8001 0:1 9:1000003 7:40001 5:1601 4:321 2:13] hashFunc:0xa701e0}
vp1_1         | 13:04:44.512 [buckettree] newBucketCache -> INFO 011 Constructing bucket-cache with max bucket cache size = [100] MBs
vp1_1         | 13:04:44.512 [buckettree] loadAllBucketNodesFromDB -> INFO 012 Loaded buckets data in cache. Total buckets in DB = [0]. Total cache size:=0
vp1_1         | 13:04:44.513 [genesis] func1 -> INFO 013 Creating genesis block.
vp1_1         | 13:04:44.514 [consensus/controller] NewConsenter -> INFO 014 Creating default consensus plugin (noops)
vp1_1         | 13:04:44.515 [consensus/statetransfer] blockThread -> INFO 015 Validated blockchain to the genesis block
vp1_1         | 13:04:44.515 [consensus/noops] newNoops -> INFO 016 NOOPS consensus type = *noops.Noops
vp1_1         | 13:04:44.515 [consensus/noops] newNoops -> INFO 017 NOOPS block size = 500
vp1_1         | 13:04:44.515 [consensus/noops] newNoops -> INFO 018 NOOPS block wait = 1s
vp1_1         | 13:04:44.515 [nodeCmd] serve -> INFO 019 Starting peer with ID=name:"vp1" , network ID=dev, address=172.17.0.4:7051, rootnodes=vp0:7051, validator=true
vp1_1         | 13:04:44.517 [rest] StartOpenchainRESTServer -> INFO 01a Initializing the REST service on 0.0.0.0:7050, TLS is disabled.
vp0_1         | 13:04:44.522 [consensus/util] RegisterChannel -> INFO 01b Registering connection from <nil>
vp1_1         | 13:04:44.521 [consensus/util] RegisterChannel -> INFO 01b Registering connection from <nil>
vp0_1         | 2016/10/28 13:08:44 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
vp1_1         | 13:08:52.712 [dockercontroller] deployImage -> ERRO 01c Error building images: The command '/bin/sh -c go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b' returned a non-zero code: 2
vp1_1         | 13:08:52.712 [dockercontroller] deployImage -> ERRO 01d Image Output:
vp1_1         | ********************
vp1_1         | Step 1 : FROM hyperledger/fabric-baseimage
vp1_1         |  ---> 4ad13274ef00
vp1_1         | Step 2 : COPY . $GOPATH/src/build-chaincode/
vp1_1         |  ---> bb1896086a91
vp1_1         | Removing intermediate container 73f59e61efa3
vp1_1         | Step 3 : WORKDIR $GOPATH
vp1_1         |  ---> Running in 010969a79f08
vp1_1         |  ---> a73cff05864e
vp1_1         | Removing intermediate container 010969a79f08
vp1_1         | Step 4 : RUN go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b
vp1_1         |  ---> Running in 4a22b5da92fe
vp1_1         | # build-chaincode
vp1_1         | src/build-chaincode/chaincode.go:123: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
vp1_1         |     *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
vp1_1         |         have Init(*shim.ChaincodeStub, string, []string) ([]byte, error)
vp1_1         |         want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
vp1_1         |
vp1_1         | ********************
vp0_1         | 13:08:52.780 [dockercontroller] deployImage -> ERRO 01c Error building images: The command '/bin/sh -c go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b' returned a non-zero code: 2
vp0_1         | 13:08:52.780 [dockercontroller] deployImage -> ERRO 01d Image Output:
vp0_1         | ********************
vp0_1         | Step 1 : FROM hyperledger/fabric-baseimage
vp0_1         |  ---> 4ad13274ef00
vp0_1         | Step 2 : COPY . $GOPATH/src/build-chaincode/
vp0_1         |  ---> 97c7c2279e28
vp0_1         | Removing intermediate container d7b92413b1cd
vp0_1         | Step 3 : WORKDIR $GOPATH
vp0_1         |  ---> Running in 6c0a7881e0dc
vp0_1         |  ---> 38743e79b358
vp0_1         | Removing intermediate container 6c0a7881e0dc
vp0_1         | Step 4 : RUN go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b
vp0_1         |  ---> Running in 88c965f24a10
vp0_1         | # build-chaincode
vp0_1         | src/build-chaincode/chaincode.go:123: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
vp0_1         |     *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
vp0_1         |         have Init(*shim.ChaincodeStub, string, []string) ([]byte, error)
vp0_1         |         want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
vp0_1         |
vp0_1         | ********************
vp1_1         | 13:08:54.928 [dockercontroller] deployImage -> ERRO 01e Error building images: The command '/bin/sh -c go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b' returned a non-zero code: 2
vp1_1         | 13:08:54.928 [dockercontroller] deployImage -> ERRO 01f Image Output:
vp1_1         | ********************
vp1_1         | Step 1 : FROM hyperledger/fabric-baseimage
vp1_1         |  ---> 4ad13274ef00
vp1_1         | Step 2 : COPY . $GOPATH/src/build-chaincode/
vp1_1         |  ---> Using cache
vp1_1         |  ---> bb1896086a91
vp1_1         | Step 3 : WORKDIR $GOPATH
vp1_1         |  ---> Using cache
vp1_1         |  ---> a73cff05864e
vp1_1         | Step 4 : RUN go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b
vp1_1         |  ---> Running in 8a8f595ea72f
vp1_1         | # build-chaincode
vp1_1         | src/build-chaincode/chaincode.go:123: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
vp1_1         |     *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
vp1_1         |         have Init(*shim.ChaincodeStub, string, []string) ([]byte, error)
vp1_1         |         want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
vp1_1         |
vp1_1         | ********************
vp1_1         | 13:08:54.928 [chaincode] Launch -> ERRO 020 launchAndWaitForRegister failed Error starting container: The command '/bin/sh -c go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b' returned a non-zero code: 2
vp0_1         | 13:08:54.949 [dockercontroller] deployImage -> ERRO 01e Error building images: The command '/bin/sh -c go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b' returned a non-zero code: 2
vp0_1         | 13:08:54.949 [dockercontroller] deployImage -> ERRO 01f Image Output:
vp0_1         | ********************
vp0_1         | Step 1 : FROM hyperledger/fabric-baseimage
vp0_1         |  ---> 4ad13274ef00
vp0_1         | Step 2 : COPY . $GOPATH/src/build-chaincode/
vp0_1         |  ---> Using cache
vp0_1         |  ---> bb1896086a91
vp0_1         | Step 3 : WORKDIR $GOPATH
vp0_1         |  ---> Using cache
vp0_1         |  ---> a73cff05864e
vp0_1         | Step 4 : RUN go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b
vp0_1         |  ---> Running in 531f7b1281fb
vp0_1         | # build-chaincode
vp0_1         | src/build-chaincode/chaincode.go:123: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
vp0_1         |     *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
vp0_1         |         have Init(*shim.ChaincodeStub, string, []string) ([]byte, error)
vp0_1         |         want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
vp0_1         |
vp0_1         | ********************
vp0_1         | 13:08:54.949 [chaincode] Launch -> ERRO 020 launchAndWaitForRegister failed Error starting container: The command '/bin/sh -c go install build-chaincode && cp src/build-chaincode/vendor/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/build-chaincode $GOPATH/bin/fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b' returned a non-zero code: 2
vp0_1         | 2016/10/28 13:09:07 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
vp0_1         | 2016/10/28 13:09:17 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
vp0_1         | 2016/10/28 13:09:17 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
vp0_1         | 2016/10/28 13:09:17 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
vp0_1         | 2016/10/28 13:09:17 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
```

The node server seems to work but still obviously can't login or anything :

```
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
info: [SDK] Initializing the blockchain
info: [SDK] Running in local mode
info: [SDK] Connected to memberservice and peer
info: [NodeJS] Express server listening at http://localhost:8080
info: [SDK] Successfully registered WebAppAdmin
info: [SDK] Going to register users
info: [SDK] Checking if redeploy is needed
info: [SDK] Going to deploy chaincode
info: [SDK] User john1 successfully registered and enrolled
info: [SDK] User jane1 successfully registered and enrolled
info: [SDK] Successfully deployed chaincode
info: [SDK] Deploy result:
{ uuid: 'fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b',
  chaincodeID: 'fa78e17c341c0b697d2636f3fb4fc6bfbe2e3edd182f1d44d903751219bbeb0b',
  result: 'TODO: get actual results; waited 20 seconds and assumed deploy was successful' }
info: [SDK] Executing after deployment
info: [SDK] Watching src/chaincode/chaincode.go for changes...
info: [TestData] Deploying Test Data
info: [TestData] Resetting indexes:
info: [SDK] submitted invoke:
{ uuid: 'bd55d682-a3d4-4f07-a8dd-941a03a0a508' }
info: [SDK] completed invoke:
{ result: 'waited 5 seconds and assumed invoke was successful' }
info: [TestData] Index reset
info: [TestData] Number of users: 2
info: [TestData] Will add new user:
info: {"userId":"john1","firstName":"John","lastName":"Doe","things":["12345678","87654321"],"salt":"c7ec977acf8b968eccfb1c9b1df5101b","hash":"6ceffdd5b4cca77b87586638eb062650c7fe5f205973c1dbe23bc9ff555ca620ae060632d2c831f3ff58cf180f664934a3cc456b9763a79ef4e506e100b4f163","address":"Dam 1, 1012 JS Amsterdam, The Netherlands","phoneNumber":"0900 0048","emailAddress":"johndoe@gmail.com"}
info: [TestData] Will add new user:
info: {"userId":"jane1","firstName":"Jane","lastName":"Doe","things":["87654321"],"salt":"09f22f5655ebf3f3dbaf0d89412f47df","hash":"0e3b353d2a52b801f65aefae40e7404d9a2abd4946d4aeac1c9e1cebcfc54fab9ab22bed059c0e8e0263dbd7d17fbb89e28c27dbcec0e4588a35cb78087e833f","address":"128 West 44th Street, New York, NY 10036, United States","phoneNumber":"0900 0024","emailAddress":"janedoe@gmail.com"}
info: [TestData] Number of things: 2
info: [TestData] Will add new Thing:
info: {"id":"12345678","description":"Lorem Ipsum"}
info: [TestData] Will add new Thing:
info: {"id":"87654321","description":"Ipsum Lorem"}
(node:2414) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest
info: [SDK] submitted invoke:
{ uuid: 'dc77eca8-b684-4960-9377-3bfb27760f09' }
info: [SDK] submitted invoke:
{ uuid: '9e9ddb4a-5267-41ad-9033-6f74d45de93d' }
info: [SDK] submitted invoke:
{ uuid: '37266a4e-fc42-47ac-9e40-82176a74a8a9' }
info: [SDK] submitted invoke:
{ uuid: '10a4fca7-1192-420f-86d1-e6b6b296e04e' }
info: [SDK] completed invoke:
{ result: 'waited 5 seconds and assumed invoke was successful' }
info: [SDK] completed invoke:
{ result: 'waited 5 seconds and assumed invoke was successful' }
info: [TestData] Added user:  jane1
info: [TestData] Added thing:  12345678
info: [SDK] completed invoke:
{ result: 'waited 5 seconds and assumed invoke was successful' }
info: [TestData] Added user:  john1
info: [SDK] completed invoke:
{ result: 'waited 5 seconds and assumed invoke was successful' }
info: [TestData] Added thing:  87654321
```

localhost:7070 #=> 

{"height":6,"currentBlockHash":"36X7z34lerZRd3LozSr/Qo6M1zX/4GoXoxhu95rwSvVM6iI5mChvOp3lptO9L07FZ3PnGY1wR+g6mJ/OKaGDMg==","previousBlockHash":"fmV/0Rtt4JJ7ZWZNEuEF00TtxMtYEXFWWj4GLG1hWd0PeZNE/tELXqNBWrMrWZXmcYbquQ9pujSWxpgLx4T34A=="}

Any help ?

**Comment by czar0** [comment]
>  # build-chaincode
> vp0_1         | src/build-chaincode/chaincode.go:123: cannot use new(SimpleChaincode) (type _SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
> vp0_1         |     *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
> vp0_1         |         have Init(_shim.ChaincodeStub, string, []string) ([]byte, error)
> vp0_1         |         want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)

@thejdavid Which version of the baseimage are you using? The boilerplate (and its chaincode) is made to work with fabric 0.5, that means version 0.0.10 for the baseimage.
_shim.ChaincodeStubInterface_ has been introduced since fabric 0.6 if I am not wrong.

A suggestion: before launching a deploy call in your network, always be sure your chaincode is deployable.
`go build` and check the output in console.

**Comment by thejdavid** [comment]
I actually had a conflict with another docker image indeed forgot that step aswell  Change tag to the fabric-baseimage: docker tag rikmoedt/fabric-baseimage hyperledger/fabric-baseimage (note: be sure you do not have already an image with the same tag, in that case, rename first the current hyperledger/fabric-baseimage to something else)
 Thanks!
